version: '3.8'

services:
  app:
    build:
      context: ./sistema
      dockerfile: Dockerfile
    container_name: sistema_java
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: bdluthieria
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bdluthieria
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
